_target_: efficiera.models.object_detection.training.pretrain.src.network.PretrainNetwork
backbone:
  _target_: efficiera.models.object_detection.training.network.backbone.resnet.ResNet
  block:
    _target_: hydra.utils.get_class
    path: efficiera.models.object_detection.training.network.block.PreActBlock
  layers: [2, 2, 2, 2]
  groups: 1
  width_per_group: 64
  quantize: ${quantize}
  in_channels: 30
  weight_quantizer: ${weight_quantizer}
  activation_quantizer: ${activation_quantizer}
  use_multiple_output: False
  downsample_method: "s2d_with_layer"
  bn_kwargs: ${training.batchnorm_kwargs}
backbone_output_channel: 512
num_classes: 1000
quantize_last_conv: ${quantize}
