model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${checkpoint_dir}
  filename: "{epoch:03d}"
  save_top_k: 1
  save_last: True
  monitor: metrics/AP50
  mode: max
  verbose: False
